# Generated by Django 4.0.5 on 2023-03-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_info',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
