# Generated by Django 4.0.5 on 2023-03-13 16:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign_mgmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('desc', models.TextField(blank=True)),
                ('key_factor', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
