# Generated by Django 4.0.5 on 2023-03-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_campaign_mgmt'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
