# Generated by Django 4.0.5 on 2023-03-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_gallery_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
