# Generated by Django 4.0.5 on 2023-03-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_slider_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slider_image',
        ),
    ]
