# Generated by Django 4.0.5 on 2023-03-11 13:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quote', ckeditor.fields.RichTextField()),
                ('address', models.TextField(blank=True)),
                ('mobile', models.IntegerField(null=True)),
                ('fb_link', models.URLField(null=True)),
                ('ln_link', models.URLField(null=True)),
                ('tw_link', models.URLField(null=True)),
            ],
        ),
    ]
