# Generated by Django 4.0.5 on 2023-03-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_info',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
