# Generated by Django 4.0.5 on 2023-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_volunteer_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_info',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
