# Generated by Django 4.0.5 on 2023-03-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_volunteer_info_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_info',
            name='ins_link',
            field=models.URLField(null=True),
        ),
    ]
